### PR TITLE
Hide lua window and run script button if device doesn't have lua

### PR DESCRIPTION
**Pull request by ryandoherty**
Addresses #1138 . Simple, 99% effective.

### CODE REVIEW

**Comment by ryandoherty** [comment]
This does leave a small grey bar at the top. Ok for beta imho.

**Comment by brentpicasso** [comment]
when reading config I see this error:  File "/home/brent/git-projects/RaceCapture_App/autosportlabs/racecapture/views/configuration/rcp/scriptview.py", line 67, in on_config_updated
    self.ids.lua_script.text = cfg.script
  File "kivy/weakproxy.pyx", line 22, in kivy.weakproxy.WeakProxy.__setattr__ (/tmp/pip_build_root/kivy/kivy/weakproxy.c:1185)
  File "kivy/weakproxy.pyx", line 15, in kivy.weakproxy.WeakProxy.__ref__ (/tmp/pip_build_root/kivy/kivy/weakproxy.c:1004)
ReferenceError: weakly-referenced object no longer exists

**Comment by brentpicasso** [comment]
Good enough for now; clearly calls for some more refactoring.  Once the error posted above is fixed :shipit:

**Comment by ryandoherty** [comment]
Error fixed.

I agree, this is not a long-term solution and it needs a rewrite, but it's solid and works for now.

**Pull request merged**
