### PR TITLE
V1.3.4 obd2 channel configurability

### PR DESCRIPTION
**Pull request by brentpicasso**
*Allow the OBD2 channels to pull in defaults for channels that match channel (min / max, etc)
*Allow further customization of channel consistent with other channel editors using ChannelNameSelectorView
*Default sample rate when adding a channel is 1Hz instead of disabled, saving a user step

### CODE REVIEW

**Comment by stieg** [comment]
Looks sane to me.  But may want to have @ryandoherty look too.

**Comment by ryandoherty** [comment]
Edge case: If you change the min/max of the OBDII channel after setting alert ranges, the circles are drawn incorrectly when editing the alert ranges after: 
http://i.imgur.com/vcMTQyQ.png

**Comment by ryandoherty** [comment]
STR: 

1) Add RPM OBDII channel, do not edit min/max
2) Save config
3) Go to dashboard screen, set alert ranges: warn: 9000-10000 , Alert: 7000-8999
4) Edit config for RPM OBDII channel, change max to 5000
5) Save config
6) Go back to dashboard, edit alert ranges, view circles super far away from the modal

**Comment by brentpicasso** [comment]
Wow. that's fancy!

**Comment by brentpicasso** [comment]
Cannot repo the customization dialog.  Used RCP sim 2.8.2 for testing.

deleted my preferences file and started with a blank config for the app, and factory defaults for RCP config.

for #2 and #5 above I interpreted "save config" as "write to RCP". Also tried saving to file just to make sure. 

What I observed was right after changing the max, writing the config and going back to the customization dialog the maxes were railed to 5000

**Comment by ryandoherty** [comment]
Weird, I'm still able to repro, here's a video: https://www.youtube.com/watch?v=HsgTxL7A7cc&feature=youtu.be

After the video I upgraded to 2.8.2, same behavior.

**Comment by brentpicasso** [comment]
Thanks, that was helpful.

On Thu, Jun 11, 2015 at 8:20 AM, Ryan Doherty <notifications@github.com>
wrote:

> Weird, I'm still able to repro, here's a video:
> https://www.youtube.com/watch?v=HsgTxL7A7cc&feature=youtu.be
>
> After the video I upgraded to 2.8.2, same behavior.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/pull/60#issuecomment-111170707>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by brentpicasso** [comment]
wow, still can't repro. will keep trying

**Comment by brentpicasso** [comment]
Ok, repro'd and pushed a fix. I suspect this fixed problems elsewhere, too.

**Comment by ryandoherty** [comment]
Looks good! :shipit:

**Pull request merged**
