### PR TITLE
V1.3.6 kivy1.9

### PR DESCRIPTION
**Pull request by brentpicasso**
kivy 1.9 support

### CODE REVIEW

**Comment by ryandoherty** [comment]
This dashboard screen looks odd http://i.imgur.com/3S47ChJ.png

**Comment by ryandoherty** [comment]
Tried to search for 'sonoma' in track list, pressed enter and nothing happens. Clicking on the magnifying glass works.

**Comment by ryandoherty** [comment]
Padding/margins broke in the status page: http://i.imgur.com/MtY3peA.png

**Comment by ryandoherty** [comment]
Code changes look good to me, just a few minor issues found.

**Comment by brentpicasso** [comment]
Fixed searching, fixed validation in analog scaling map editor resulting from changes in kivy 1.9

Could not repro dashboard view issue anywhere....

**Comment by ryandoherty** [comment]
Can't repro dashboard bug anymore, :shipit:

**Pull request merged**
