### PR TITLE
Further scaling fixes

### PR DESCRIPTION
**Pull request by paulbutcher**
This PR fixes the scaling of the remaining dashboard views.

The configuration view are still TBD

### CODE REVIEW

**Comment by brentpicasso** [comment]
This all looks great; one thing in the raw channels view I'd like to see the channel labels a bit smaller vs the data so the things you want to see are visually more pronounced. Thoughts?

**Comment by paulbutcher** [comment]
That makes sense. Do you want that for only the raw channel view? Or for all digital gauges (i.e. for the three gauges at the bottom of each dashboard view too)?

**Comment by brentpicasso** [comment]
Good point about all of the digital gauges.  So yes. Thanks!

On Sat, Mar 28, 2015 at 11:06 AM, Paul Butcher <notifications@github.com>
wrote:

> That makes sense. Do you want that for only the raw channel view? Or for
> all digital gauges (i.e. for the three gauges at the bottom of each
> dashboard view too)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autosportlabs/RaceCapture_App/pull/28#issuecomment-87275025>
> .
>



-- 
Brent Picasso
*Autosport Labs <http://www.autosportlabs.com>*
*Technology for Race and Street*

**Comment by paulbutcher** [comment]
Done. I also fixed something I missed first time around (scaling the "No Data" message on the raw channel view).

**Comment by brentpicasso** [comment]
Looks good!

**Pull request merged**
