### PR TITLE
Fire rcpapi callbacks on UI thread

### PR DESCRIPTION
**Pull request by ryandoherty**
Hey look, this is just like JavaScript closures and scope!

### CODE REVIEW

**Comment by brentpicasso** [comment]
Good update. 

To go full circle on this refactoring, can we also clean up everywhere in the code that separately executes a Clock.schedule..()

**Comment by brentpicasso** [comment]
Also, this should be in 1.7.1, yes?

**Comment by ryandoherty** [comment]
Oops, didn't change the branch. Will merge into 1.7.1 manually. afaict the rest of the callbacks in rcpapi are fine.

**Comment by brentpicasso** [comment]
Sorry, I meant - everywhere else in the code where we wrap rc_api responses in Clock.schedule..() to make it threadsafe - recommend removing those redundant Clock.schedule..() calls as part of this refactoring.

**Comment by ryandoherty** [comment]
Oh, do you mean code outside of rcpapi.py? If so I will file a ticket.

**Comment by ryandoherty** [comment]
Closing this PR, changes were merged into 1.7.1

**Pull request closed without merging**
