### PR TITLE
Improvements to firmware update screen

### PR DESCRIPTION
**Pull request by brentpicasso**
* Prompt user to save config as necessary
* Hid not working button (check for update online)

### CODE REVIEW

**Comment by brentpicasso** [comment]
fixes #818

**Comment by ryandoherty** [comment]
The popup happens after the user has select the firmware file, I think it should show up when they click on the 'Update Firmware' button. That way they don't waste time finding their firmware image to then realize they need to backup their config. Thoughts?

**Comment by brentpicasso** [comment]
Agreed. flipped the order and made other improvements. thank you.

**Comment by ryandoherty** [comment]
:shipit:

**Pull request merged**
