### PR TITLE
Add print Tx/Rx serial stream arg to app without setting Trace

### PR DESCRIPTION
**Pull request by stieg**
More than a few times I have needed a way to see what was being sent
to and from RCP.  Before this patch the only way I could do this was
to enable Trace level logging (which is not easy to do unfortunately).
But the problem with this is that if I enable Trace level debugging, I
get TONS of logs.  Metric TONS.

That is not helpful to me.  So instead I wrote this patch that will
allow me to extract out the Tx/Rx data by passing the following arg

./main.py -- --print_tx_rx

### CODE REVIEW

**Comment by brentpicasso** [comment]
Can we see if we can change it from trace to debug level provides a reasonable balance?

**Comment by stieg** [comment]
We could.  Kivy supports passing the -d flag on the initial parameters so that satisfies my requirement of having this be trigger able from the command line.  I'll do this in another PR.

**Comment by stieg** [comment]
Debug Review: autosportlabs/RaceCapture_App/pull/859

**Comment by stieg** [comment]
So that works.  Only drawback is that its showing data not necessarily relevant to debugging the app itself, but that is a gray line.  If you like autosportlabs/RaceCapture_App#859 better... go with it and close this one.  Doesn't matter to me.

**Pull request closed without merging**
