### PR TITLE
fixed parsing error where 32 and higher channels are present

### PR DESCRIPTION
**Pull request by brentpicasso**
App fails to parse data stream if >= 32 channels are present in the stream.

### CODE REVIEW

**Comment by brentpicasso** [comment]
You can test with this script, then watch the dashboard

setTickRate(10)
count = 20

A = {}
for v = 1, count do
A[v] = addChannel("Virtual" ..v, 10)
end

value = 0
function onTick()
 for i = 1, #A do
  setChannel(A[i], value * i)
 end
  value=value+1
  if value > 200 then value = 0 end
end

**Comment by ryandoherty** [comment]
This is weird, I set the count to 33 and my dash looks like this:

![Dash]
(http://i.imgur.com/jtCQ4RT.png)

**Comment by brentpicasso** [comment]
I put a trivial fix on this view to enable scrolling in master. I just merged it with this branch. Can you pull from this branch and test again?

**Comment by ryandoherty** [comment]
Looks good!

![scroll]
(http://i.imgur.com/6t6byiq.png)

I do think there's a bug if there are too few channels the digital dash sizes things incorrectly thought.

**Pull request merged**
