### PR TITLE
Remove delay when clicking/tapping 'Send telemetry' button in app preferences

### LINKED ISSUE #1184: Responsiveness of BT <-> wifi switch
The touch response seems poor for this button.  Investigate why and resolve.

Possible reasons: UI thread is blocked when the switch is activated.

### PR DESCRIPTION
**Pull request by ryandoherty**
Seems to work better now, UI still shows a blue background color for a second, which we have no control over afaik. 

Fixes #1184

### CODE REVIEW

**Comment by brentpicasso** [comment]
#1184 actually is a different problem, observed when switching from BT to WiFi (app seems to hang for a while).  I've also observed this one as a separate issue (button responsiveness) but I don't think we're tracking an issue.

**Comment by ryandoherty** [comment]
Oh wow, I confused the two, oops. This change is still nice though! :P

**Comment by brentpicasso** [comment]
Yeah totally important!  I'll review in the meantime.  Should get it's own issue too. :)

**Comment by brentpicasso** [comment]
:shipit:

**Pull request merged**
