### PR TITLE
ensure session is renamed in session list after editing.

### LINKED ISSUE #1212: renaming session does not reflect in session list
STR: 

load a sessoin into the immediate list
rename the session
observe, session is not renamed in list

### PR DESCRIPTION
**Pull request by brentpicasso**
resolves #1212

### CODE REVIEW

**Comment by ryandoherty** [comment]
This does rename the session in the session list, but laps loaded don't update their session name: http://i.imgur.com/gHTkDCf.png

**Comment by brentpicasso** [comment]
good catch. can resolve.

**Comment by brentpicasso** [comment]
@ryandoherty  ok, session name updates in analysis map legend and in channelvaluesview. 

sorry for the additional whitespace changes.

**Comment by ryandoherty** [comment]
:shipit: !

**Pull request merged**
