### PR TITLE
migrate to kivy 1.9.1

### PR DESCRIPTION
**Pull request by brentpicasso**
* Updated dependencies
* Update instructions

### CODE REVIEW

**Comment by brentpicasso** [comment]
It looks like with Kivy 1.9.1 all you need to do is:

Uninstall custom ASL 1.9.0 kivy 
(Hint on how to do that is here:
http://askubuntu.com/questions/38692/how-does-one-remove-applications-installed-through-python-setup-py-install)

sudo pip install kivy --upgrade
sudo pip install Cython==0.21.2

**Comment by brentpicasso** [comment]
addresses #797

**Comment by ryandoherty** [comment]
Got this when trying to view the Script section of the Config view:

```
[CRITICAL] [CrashHandler] Caught exception in Kivy loop: 'NoneType' object has no attribute '__getitem__'
[CRITICAL] [Traceback (most recent call last)]
  File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/core/window/window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/core/window/window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/base.py", line 333, in idle
    Builder.sync()
  File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/lang.py", line 2194, in sync
    call_fn(next_args[:-1], None, None)
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by ryandoherty** [comment]
Getting some weird mouse behavior in the analysis view: https://www.youtube.com/watch?v=obObToaWn3o&feature=youtu.be

**Comment by brentpicasso** [comment]
Does the mouse issue happen upon a fresh lap selection after a fresh run of the app?  Can't repo on Linux.

**Comment by brentpicasso** [comment]
No repro on scripting view on linux..

**Comment by ryandoherty** [comment]
Mouse issue occurs regardless of lap selection steps.

**Comment by brentpicasso** [comment]
Not ready for 1.9.1 yet.

**Pull request closed without merging**
